[2024-05-28T08:55:07.463+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T08:55:07.513+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: oltp_to_olap_all_transform.create_FRM_table manual__2024-05-28T08:54:22.880138+00:00 [queued]>
[2024-05-28T08:55:07.533+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: oltp_to_olap_all_transform.create_FRM_table manual__2024-05-28T08:54:22.880138+00:00 [queued]>
[2024-05-28T08:55:07.534+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 0
[2024-05-28T08:55:07.559+0000] {taskinstance.py:2330} INFO - Executing <Task(BigQueryInsertJobOperator): create_FRM_table> on 2024-05-28 08:54:22.880138+00:00
[2024-05-28T08:55:07.573+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=540) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T08:55:07.577+0000] {standard_task_runner.py:63} INFO - Started process 542 to run task
[2024-05-28T08:55:07.578+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'oltp_to_olap_all_transform', 'create_FRM_table', 'manual__2024-05-28T08:54:22.880138+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/oltp_olap.py', '--cfg-path', '/tmp/tmpbd2hj_o1']
[2024-05-28T08:55:07.589+0000] {standard_task_runner.py:91} INFO - Job 205: Subtask create_FRM_table
[2024-05-28T08:55:07.681+0000] {task_command.py:426} INFO - Running <TaskInstance: oltp_to_olap_all_transform.create_FRM_table manual__2024-05-28T08:54:22.880138+00:00 [running]> on host 9b03efc10d80
[2024-05-28T08:55:07.865+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ngquynh' AIRFLOW_CTX_DAG_ID='oltp_to_olap_all_transform' AIRFLOW_CTX_TASK_ID='create_FRM_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T08:54:22.880138+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T08:54:22.880138+00:00'
[2024-05-28T08:55:07.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T08:55:07.902+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-28T08:55:07.906+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-28T08:55:07.995+0000] {bigquery.py:2832} INFO - Executing: {'query': {'query': "DECLARE today_date DATE DEFAULT DATE '1998-05-06';\n\n-- Tạo bảng RFM_table\nCREATE OR REPLACE TABLE `marine-catalyst-419003.transformed.RFM_table` AS\nWITH RFM_table AS (\n  SELECT\n    orders.customer_id,\n    MAX(CAST(orders.order_date AS DATE)) AS LastPurchaseDate,\n    COUNT(DISTINCT orders.order_id) AS TotalTransaction,\n    SUM(order_details.quantity * order_details.unitPrice * (1 - order_details.discount)) AS Monetary\n  FROM\n    `marine-catalyst-419003.demo.orders` AS orders\n  JOIN\n    `marine-catalyst-419003.transformed.Dim_Order_details` AS order_details\n  ON\n    orders.order_id = order_details.orderID\n  GROUP BY\n    orders.customer_id\n)\n\n-- Thêm các cột điểm vào bảng mới\nSELECT\n  customer_id,\n  DATE_DIFF(today_date, LastPurchaseDate, DAY) AS Recency,\n  TotalTransaction AS Frequency,\n  Monetary,\n  NULL AS recency_score, -- Khởi tạo cột recency_score với giá trị NULL\n  NULL AS frequency_score, -- Khởi tạo cột frequency_score với giá trị NULL\n  NULL AS monetary_score -- Khởi tạo cột monetary_score với giá trị NULL\nFROM\n  RFM_table\nWHERE\n  Monetary > 0;\n\nselect * from `marine-catalyst-419003.transformed.RFM_table`\nwhere customer_id = 'ANTON'", 'useLegacySql': False}}'
[2024-05-28T08:55:07.997+0000] {bigquery.py:1660} INFO - Inserting job ***_oltp_to_olap_all_transform_create_FRM_table_2024_05_28T08_54_22_880138_00_00_b25938d12c137bc376a025ed825135cc
[2024-05-28T08:55:16.708+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T08:55:16.710+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2891, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1626, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1595, in is_job_done
    self._reload_query_results(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1426, in _reload_query_results
    self._query_results = self._client._get_query_results(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2015, in _get_query_results
    resource = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/datawarehouse-423912/queries/airflow_oltp_to_olap_all_transform_create_FRM_table_2024_05_28T08_54_22_880138_00_00_b25938d12c137bc376a025ed825135cc?maxResults=0&location=US&prettyPrint=false: Access Denied: Table marine-catalyst-419003:demo.orders: User does not have permission to query table marine-catalyst-419003:demo.orders, or perhaps it does not exist in location US. at [4:1]

Location: US
Job ID: airflow_oltp_to_olap_all_transform_create_FRM_table_2024_05_28T08_54_22_880138_00_00_b25938d12c137bc376a025ed825135cc

[2024-05-28T08:55:16.736+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=oltp_to_olap_all_transform, task_id=create_FRM_table, run_id=manual__2024-05-28T08:54:22.880138+00:00, execution_date=20240528T085422, start_date=20240528T085507, end_date=20240528T085516
[2024-05-28T08:55:16.763+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 205 for task create_FRM_table (400 GET https://bigquery.googleapis.com/bigquery/v2/projects/datawarehouse-423912/queries/airflow_oltp_to_olap_all_transform_create_FRM_table_2024_05_28T08_54_22_880138_00_00_b25938d12c137bc376a025ed825135cc?maxResults=0&location=US&prettyPrint=false: Access Denied: Table marine-catalyst-419003:demo.orders: User does not have permission to query table marine-catalyst-419003:demo.orders, or perhaps it does not exist in location US. at [4:1]

Location: US
Job ID: airflow_oltp_to_olap_all_transform_create_FRM_table_2024_05_28T08_54_22_880138_00_00_b25938d12c137bc376a025ed825135cc
; 542)
[2024-05-28T08:55:16.794+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T08:55:16.815+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T08:55:16.819+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
