[2024-05-28T11:20:58.157+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T11:20:58.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loading_to_bigquerry.load_employees_to_bq manual__2024-05-28T11:19:54.427040+00:00 [queued]>
[2024-05-28T11:20:58.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loading_to_bigquerry.load_employees_to_bq manual__2024-05-28T11:19:54.427040+00:00 [queued]>
[2024-05-28T11:20:58.208+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 0
[2024-05-28T11:20:58.237+0000] {taskinstance.py:2330} INFO - Executing <Task(GCSToBigQueryOperator): load_employees_to_bq> on 2024-05-28 11:19:54.427040+00:00
[2024-05-28T11:20:58.274+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1079) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T11:20:58.277+0000] {standard_task_runner.py:63} INFO - Started process 1081 to run task
[2024-05-28T11:20:58.278+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loading_to_bigquerry', 'load_employees_to_bq', 'manual__2024-05-28T11:19:54.427040+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/load_to_bigquerry.py', '--cfg-path', '/tmp/tmp6s7e6ndw']
[2024-05-28T11:20:58.287+0000] {standard_task_runner.py:91} INFO - Job 308: Subtask load_employees_to_bq
[2024-05-28T11:20:58.376+0000] {task_command.py:426} INFO - Running <TaskInstance: loading_to_bigquerry.load_employees_to_bq manual__2024-05-28T11:19:54.427040+00:00 [running]> on host 9b03efc10d80
[2024-05-28T11:20:58.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ngquynh' AIRFLOW_CTX_DAG_ID='loading_to_bigquerry' AIRFLOW_CTX_TASK_ID='load_employees_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T11:19:54.427040+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T11:19:54.427040+00:00'
[2024-05-28T11:20:58.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T11:20:58.546+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-28T11:20:58.550+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-28T11:20:58.553+0000] {gcs_to_bigquery.py:380} INFO - Using existing BigQuery table for storing data...
[2024-05-28T11:20:58.660+0000] {gcs_to_bigquery.py:384} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'datawarehouse-423912', 'datasetId': 'warehouse', 'tableId': 'employees'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://warehouse8/dataupdated/employees.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': True, 'schema': {'fields': [{'name': 'employeeId', 'type': 'INTERGER', 'mode': 'NULLABLE'}, {'name': 'lastName', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'firstName', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'title', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'titleOfCourtesy', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'birthDate', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}, {'name': 'hireDate', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}, {'name': 'address', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'city', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'region', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'postalCode', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'country', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'homePhone', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'extension', 'type': 'INTERGER', 'mode': 'NULLABLE'}, {'name': 'photo', 'type': 'FLOAT', 'mode': 'NULLABLE'}, {'name': 'notes', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'reportsTo', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'photoPath', 'type': 'STRING', 'mode': 'NULLABLE'}]}, 'maxBadRecords': 10, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-05-28T11:20:58.666+0000] {bigquery.py:1660} INFO - Inserting job ***_loading_to_bigquerry_load_employees_to_bq_2024_05_28T11_19_54_427040_00_00_fd4a8071d18c84978e265db7631e0709
[2024-05-28T11:21:06.490+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T11:21:06.491+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 385, in execute
    job: BigQueryJob | UnknownJob = self._submit_job(self.hook, job_id)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 307, in _submit_job
    return hook.insert_job(
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 486, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1663, in insert_job
    job_api_repr._begin()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/datawarehouse-423912/jobs?prettyPrint=false: Invalid value for type: INTERGER is not a valid value
[2024-05-28T11:21:06.531+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=loading_to_bigquerry, task_id=load_employees_to_bq, run_id=manual__2024-05-28T11:19:54.427040+00:00, execution_date=20240528T111954, start_date=20240528T112058, end_date=20240528T112106
[2024-05-28T11:21:06.569+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 308 for task load_employees_to_bq (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/datawarehouse-423912/jobs?prettyPrint=false: Invalid value for type: INTERGER is not a valid value; 1081)
[2024-05-28T11:21:06.608+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T11:21:06.665+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T11:21:06.673+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
